import React from 'react'
import { View, Text,StyleSheet } from 'react-native'
var styles = StyleSheet.create({
    container: {flex: 1, backgroundColor: '#fff'},
    linearGradient: {
      height: 321,
    },
    txtwelcome: {
      alignSelf: 'flex-start',
      marginLeft: 24,
      fontSize: 49,
      fontFamily: 'Mosk Bold 700',
      color: '#fff',
    },
    txtnote: {
      alignSelf: 'flex-start',
      marginLeft: 24,
      fontSize: 12,
      fontFamily: 'Mosk Medium 500',
      color: '#fff',
      marginTop: 4,
    },
    viewtong: {marginTop: 28, paddingLeft: 20, flex: 1, paddingRight: 20},
    view1: {
      backgroundColor: '#fff',
      borderRadius: 10,
      paddingTop: 34,
      paddingRight: 27,
      paddingLeft: 27,
      shadowColor: '#000',
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
      height: 385,
    },
    view2: {alignItems: 'center', justifyContent: 'center'},
    viewbogoc: {
      width: 80,
      height: 80,
      borderRadius: 80 / 2,
      shadowColor: '#000',
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
    },
    linerbogoc: {
      width: 70,
      height: 70,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 70 / 2,
    },
    viewcardlogin: {
   
      flexDirection: 'row',
      backgroundColor: '#fff',
    },
    viewgoogle: {
      alignSelf:'center',
      width: 70,
      marginTop: 40,
      height: 70,
      shadowColor: '#000',
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
      borderRadius: 70 / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
    },
    viewfb: {
      width: 70,
      marginTop: 40,
      marginLeft: 16,
      marginRight: 16,
      height: 70,
      borderRadius: 70 / 2,
      shadowColor: '#000',
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
      borderRadius: 70 / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
    },
    viewtwiter: {
      width: 70,
      marginTop: 40,
      height: 70,
      borderRadius: 70 / 2,
      shadowColor: '#000',
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 12,
      borderRadius: 70 / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
    },
  });
export default styles;
